### ISSUE TITLE
runtime errors /w latest updates

### ISSUE THREAD

**Issue by davidsanner** [Asw1n/advancedwind#2]
Seeing this when I run advancedwind on Signal K Server version 2.12.0  - even w/ a clean install/removing plugin-config-data/AdvancedWind.json

Something w/ my setup   (Rpi5 / debian 12.8 / node v18.19.0 ) or are others seeing this?

TypeError: Cannot read properties of undefined (reading 'forEach') at /home/pi/.signalk/node_modules/advancedwind/pluginUtils.js:204:25 at Array.forEach (<anonymous>) at Array.<anonymous> (/home/pi/.signalk/node_modules/advancedwind/pluginUtils.js:200:21) at DeltaChain.doProcess (/usr/local/lib/node_modules/signalk-server/lib/deltachain.js:18:26) at DeltaChain.process (/usr/local/lib/node_modules/signalk-server/lib/deltachain.js:11:21) at Server.app.handleMessage (/usr/local/lib/node_modules/signalk-server/lib/index.js:233:38) at Object.handleMessage (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:225:17) at appCopy.registerPutHandler (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:425:21) at new SignalKOnDelta (/home/pi/.signalk/node_modules/@signalk/node-red-embedded/signalk-put-handler.js:14:21) at Object.createNode (/home/pi/.signalk/node_modules/@node-red/runtime/lib/flows/util.js:190:27) at Flow.start (/home/pi/.signalk/node_modules/@node-red/runtime/lib/flows/Flow.js:261:54) at async Object.start [as startFlows] (/home/pi/.signalk/node_modules/@node-red/runtime/lib/flows/index.js:403:17)

**Comment by Asw1n** [comment]
The problem arises when the plugin is disabled. It should be tackled in release 2.1.2
Can you confirm this?

**Comment by davidsanner** [comment]
Currently running 2.1.2 - I'm getting these errors when the plugin is enabled, not disabled.  And w/ this version I'm not seeing any output in the Data Browser.  Prev 1.x versions worked well.

**Comment by Asw1n** [comment]
I think I found and fixed the bug. 
I could not reproduce the bug myself so I am depending on you for confirmation.

**Comment by davidsanner** [comment]
Sorry, but it seems to have the same output / bug.

TypeError: Cannot read properties of undefined (reading 'forEach') at /home/pi/.signalk/node_modules/advancedwind/pluginUtils.js:205:25 at Array.forEach (<anonymous>) at Array.<anonymous> (/home/pi/.signalk/node_modules/advancedwind/pluginUtils.js:201:22) ...

I went ahead and did a clean install of signalk & advanced wind but no luck.
Is there some sort of tests / basic debug tests I can run on my end ... if that would help.

Thx.

**Comment by davidsanner** [comment]
Couple more tests... super clean install, including new .signalk dir starting from scratch and adding only plugins that I'm using.  (settings/defaults/baseDeltas all the same).  Clean system install of signalk as well (ver 2.12.0 ).

Now, when I restart signalk, I get several of the TypeErrors that I've been seeing but they no longer repeat.  If I start signalk with AdvancedWind disables I don't see these errors and when I enable it seems to work fine, no errors (unless I restart signalk).

Seems unlikely but figured I'd mentioned that I have derived-data running and Source Priorities Settings for AdvancedWind vs derived-data.

Finally at signalk startup I get 8 errors right away and then 1 more about 7 seconds later but no more after that.   All the same TypeErrors from  ..../node_modules/advancedwind/pluginUtils.js:205:25   I see a few more when I have node-red enabled.  

I hope some of this helps - Thanks again.

**Comment by Asw1n** [comment]
David,
Thanks for all the tests and the patience.

Some insight to the problem. The plugin uses two different ways to get deltas from the server. THe first method is to subscribe to deltas. I used this method in version 1. The downside of this method is that it duplicates apparent wind, thae original deltas remain available and the plugin adds deltas when publishing corrected apparent wind values.
In version 2 I switched from the subscribe method to a getDeltaInputHandler (only for apparent wind, not for the other deltas). This allows the plugin to catch the original apparent wind and replace it with a corrected apparent wind. There are no longer duplicate values that might mess up some other plugins or instrument displays.
The DeltaInputHandler sometimes gets Deltas that are structured differently than is expected and the plugin crashes. I had this at startup and I thought I had tackled it. But is seems that in your configuration there are other variants of the delta structure that still causes problems. It could be a delta describing source priority, but I have not tested that jet.

What I did change in version 2.1.4 though is to add another evaluation of the delta structure that might prevent the problem. But, I am not sure as I still have not reproduced your problem. I also added the option to switch back to the old method of getting the apparent wind. There now is the "Replace apparent wind" option that is set to true by default. The plugin then uses the DeltaInputHandler. If set is to false the plugin will use the old method that does not give you problems.

Oh, there is no need to start all over with a clean installation.

**Comment by davidsanner** [comment]
Thanks for the detailed description.  

Looks like the changes to the evaluation of the delta structure did the trick, at least for my setup, as I'm not seeing any errors on startup or running!  I tested 'Replace apparent wind' being checked and unchecked and works as expected (nice option) & no errors w/ either setting.
Thanks for for your plugin and getting it going for my setup as well.

Now I just need to go sailing so I check it out in action.

(btw, my 'clean install' turned out to be a good thing as it cleaned up / reduced the size of my node_modules dir - I saved the settings so I just needed to add back the plugins I'm actively using.)
